name: Update Kayo Playlist

on:
  schedule:
    - cron: '0 */8 * * *'  # Run every 8 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python kayo_scraper.py

    - name: Debug file changes
      run: |
        ls -l kayo_channels.m3u
        ls -l kayo_epg.xml
        cat kayo_channels.m3u
        cat kayo_epg.xml

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if files have changed
        git add kayo_channels.m3u kayo_epg.xml
        git status
        git diff --cached --quiet || git commit -m "Update Kayo playlist and EPG"
        git push
